"""add_recurring_event_fields

Revision ID: 660ceb4aaf00
Revises: 
Create Date: 2025-10-22 23:55:11.360548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660ceb4aaf00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('events', sa.Column('recurring', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('events', sa.Column('weekdays', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('parent_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'events', 'events', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'parent_id')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'weekdays')
    op.drop_column('events', 'recurring')
    # ### end Alembic commands ###
