"""diagnose event_members

Revision ID: e8e998577d55
Revises: 4c10382c68a3
Create Date: 2025-11-18 00:02:11.117328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e998577d55'
down_revision: Union[str, Sequence[str], None] = '4c10382c68a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_members',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )
    op.create_index(op.f('ix_event_members_event_id'), 'event_members', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_members_id'), 'event_members', ['id'], unique=False)
    op.create_index(op.f('ix_event_members_user_id'), 'event_members', ['user_id'], unique=False)
    op.add_column('events', sa.Column('attendance_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attendance_threshold')
    op.drop_index(op.f('ix_event_members_user_id'), table_name='event_members')
    op.drop_index(op.f('ix_event_members_id'), table_name='event_members')
    op.drop_index(op.f('ix_event_members_event_id'), table_name='event_members')
    op.drop_table('event_members')
    # ### end Alembic commands ###
